name: Build Docker Image

on:
  push:
    branches: ["main"]
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build Docker image
        run: docker build -t area-app .

      - name: Tag image
        run: docker tag area-app:latest ${{ secrets.ECR_REGISTRY }}/area-app:latest

      - name: Push image to ECR
        run: docker push ${{ secrets.ECR_REGISTRY }}/area-app:latest
      